example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_xml, show_json, show_xml_by_id, show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax, submit_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', submit_ajax, name='submit_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from wishlist.models import BarangWishlist

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Naila',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Naila',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def submit_ajax(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        BarangWishlist.objects.create(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi,
        )
    else:
        messages.info(request, 'Data gagal disimpan')
    return HttpResponseRedirect(reverse('wishlist:show_wishlist_ajax'))

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
  <style>
    body {
        text-align: center;        
    }

    li {
      list-style: none;
    }

    table {
        margin-left: auto;
        margin-right: auto;
    }

    .btn {
        text-align: center;
    }

    tr {
        height: 50px;
    }
</style>
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<style>
    body {
        background-image: url("https://i.pinimg.com/564x/79/ab/d7/79abd72250c0004e626c1fa1986c9f35.jpg");
    }

    .card-body {
        background-color: white;
        border-radius: 12px;
        padding: 50px;
        margin: auto;
        margin-top: 10%;
        width: 50%;
        height: 80%;
    }
</style>
{% endblock meta %}

{% block content %}

<div class = "login card-body">

    <h1>Login</h1><br>

    <form class="" method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

        </table><br>
        <input class="btn btn-primary login_btn" type="submit" value="Login">
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <br>
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
<style>
    body {
        background-image: url("https://i.pinimg.com/564x/15/1e/a8/151ea8d292b2a527d0a817f70cbe863d.jpg");
    }

    .card-body {
        background-color: white;
        border-radius: 20px;
        padding: 50px;
        margin: auto;
        margin-top: 3%;
        width: 70%;
        height: 80%;
    }

    td {
        margin: 20px;
        padding: 15px;
    }
</style>
{% endblock meta %}

{% block content %}  

<div class = "login card-body">
    
    <h1>Formulir Registrasi</h1><br>

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}
            </table>  
            <br>
            <input class="btn btn-primary" type="submit" name="submit" value="Daftar"/>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<title>Wishlist</title>
<style>
    .card-body {
        background-color: white;
        border-radius: 12px;
        padding: 50px;
        margin: auto;
        margin-top: 3%;
        width: 90%;
        height: 80%;
    }

    body {
        background-image: url("https://i.pinimg.com/564x/46/a3/ab/46a3ababf0560305c98f9487511be611.jpg");
    }

    td {
        margin: 20px;
        padding: 15px;
    }

    thead {
        background-color: #ffc7f3;
    }

    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    .styled-table tr:last-of-type {
        border-bottom: 2px solid #ca1fa5;
    }

    .styled-table th {
        padding: 20px;
        margin: 20px;
    }

    .container {
        border-radius: 12px;
    }

</style>
{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ nama }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item d-flex">
          </li>
        </ul>
        <form class="d-flex">
            <a class="nav-link active" style="color: red;" aria-current="page" href="{% url 'wishlist:logout' %}">Logout</a>
        </form>
      </div>
    </div>
  </nav>

<div class="card-body">
    <h1>Wishlist</h1><br>

    <div class="container-md">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Nama Barang</th>
                    <th>Harga Barang</th>
                    <th>Deskripsi</th>
                </tr>
            </thead>
            <tbody>
                {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                {% for barang in list_barang %}
                <tr>
                    <th>{{barang.nama_barang}}</th>
                    <th>{{barang.harga_barang}}</th>
                    <th>{{barang.deskripsi}}</th>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
    <br><br>
    <h6>Sesi terakhir login: {{ last_login }}</h6>
</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
    <title>Wishlist</title>
    <style>
        .card-body {
            background-color: white;
            border-radius: 12px;
            padding: 50px;
            margin: auto;
            margin-top: 3%;
            width: 90%;
            height: 80%;
            margin-bottom: 30px;
        }

        body {
            background-image: url("https://i.pinimg.com/564x/46/a3/ab/46a3ababf0560305c98f9487511be611.jpg");
        }

        td {
            margin: 20px;
            padding: 15px;
        }

        thead {
            background-color: #ffc7f3;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

        .styled-table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }

        .styled-table tr:last-of-type {
            border-bottom: 2px solid #ca1fa5;
        }

        .styled-table th {
            padding: 20px;
            margin: 20px;
        }

        .container {
            border-radius: 12px;
        }

    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $.getJSON( "http://localhost:8000/wishlist/json/", function( data ) {
            data.forEach(element => {
                $("tbody").append("<tr><td>" + element.fields.nama_barang + 
                                "</td><td>" + element.fields.harga_barang + 
                                "</td><td>" + element.fields.deskripsi + 
                                "</td></tr>");
            });
        });

        $(document).ready(function () {
            event.preventDefault();
            var formData = $("form").serialize();
            $.ajax({
                type: "POST",
                url: event.currentTarget.action,
                data: formData,
                dataType: "json",
                encode: true,
            }).done(function (data) {
                console.log(data);
            })
        });
    </script>

{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ nama }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item d-flex">
          </li>
        </ul>
        <form class="d-flex">
            <a class="nav-link active" style="color: red;" aria-current="page" href="{% url 'wishlist:logout' %}">Logout</a>
        </form>
      </div>
    </div>
  </nav>

<div class="card-body">
    <h1>Wishlist</h1><br>
    <div class="container-md">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Nama Barang</th>
                    <th>Harga Barang</th>
                    <th>Deskripsi</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <br><br>

    <div class="form-group container border mb-5" style="width:fit-content; background-color: #ffc7f3;">
        <h4 class="m-3">Add New Wishlist</h4>
        <form action="{% url 'wishlist:submit_ajax' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" name="nama_barang" placeholder="Name">
            </div>
            <div class="mb-3">
                <input type="number" class="form-control" name="harga_barang" placeholder="Price">
            </div>
            <div class="mb-3">
                <textarea class="form-control" rows="3" name="deskripsi" placeholder="Description"></textarea>
            </div>
            <div class="mb-3">
                <input type="submit" class=".button btn btn-primary mb-3" value="Add Wishlist">
            </div>
        </form>
    </div>
    <h6 class="mt-5">Sesi terakhir login: {{ last_login }}</h6>
</div>

{% endblock content %}